name: ideal
version: 0.0.1
license: MIT
author: "Joona Piirainen"
copyright: "2024 Joona Piirainen"

dependencies:
  - base >= 4.17.2.1

ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures

executables:
  ideal:
    main: bin/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
