name: ideal
version: 0.0.1
license: MIT
author: "Joona Piirainen"
copyright: "2024 Joona Piirainen"

ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures

dependencies:
  - base >= 4.17.2.1

library:
  source-dirs: src
  # dependencies:

executables:
  ideal:
    main: bin/Main.hs
    dependencies:
      - ideal
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
