[package]
name = "website"
version.workspace = true
edition.workspace = true

[dependencies]
interpreter = { path = "../interpreter" }
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.77", features = [
  "Window",
  "Document",
  "HtmlElement",
  "Text",
] }
