name: ideal ci

on:
  push:
    branches:
      - '**'

jobs:
  flake-check:
    runs-on: ubuntu-latest
    name: Nix flake check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Run nix flake check
        run: nix flake check --all-systems
